/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param password 
 * @param passwordConfirmation 
 */
@JsonClass(generateAdapter = true)

data class AccountsUsersAuthPasswordResetPostRequest (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "password_confirmation")
    val passwordConfirmation: kotlin.String

) {


}

