/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time 
 * @param isWatched 
 * @param releaseEpisodeId 
 */
@JsonClass(generateAdapter = true)

data class AccountsUsersMeViewsTimecodesPostRequestInner (

    @Json(name = "time")
    val time: java.math.BigDecimal,

    @Json(name = "is_watched")
    val isWatched: kotlin.Boolean,

    @Json(name = "release_episode_id")
    val releaseEpisodeId: java.util.UUID

) {


}

