/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.EnumsanimereleasesreleaseageRating
import anilibria.apigen.models.Enumsanimereleasesreleasetype

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param genres Список идентификаторов жанров
 * @param types Список типов релизов
 * @param years Минимальный год выхода релиза
 * @param search Поисковый запрос
 * @param ageRatings Список возрастных рейтингов
 */
@JsonClass(generateAdapter = true)

data class AccountsUsersMeCollectionsReleasesPostRequestF (

    /* Список идентификаторов жанров */
    @Json(name = "genres")
    val genres: kotlin.String? = null,

    /* Список типов релизов */
    @Json(name = "types")
    val types: kotlin.collections.List<Enumsanimereleasesreleasetype>? = null,

    /* Минимальный год выхода релиза */
    @Json(name = "years")
    val years: kotlin.String? = null,

    /* Поисковый запрос */
    @Json(name = "search")
    val search: kotlin.String? = null,

    /* Список возрастных рейтингов */
    @Json(name = "age_ratings")
    val ageRatings: kotlin.collections.List<EnumsanimereleasesreleaseageRating>? = null

) {


}

