/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsaccountsusersusercollectiontype

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param releaseId 
 * @param typeOfCollection 
 */
@JsonClass(generateAdapter = true)

data class AccountsUsersMeCollectionsPostRequestInner (

    @Json(name = "release_id")
    val releaseId: kotlin.Int,

    @Json(name = "type_of_collection")
    val typeOfCollection: Enumsaccountsusersusercollectiontype

) {


}

