/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fromYear 
 * @param toYear 
 */
@JsonClass(generateAdapter = true)

data class AnimeCatalogReleasesPostRequestFYears (

    @Json(name = "from_year")
    val fromYear: kotlin.Int? = null,

    @Json(name = "to_year")
    val toYear: kotlin.Int? = null

) {


}

