/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.AnimeCatalogReleasesPostRequestFYears
import anilibria.apigen.models.EnumsanimecatalogfilterproductionStatus
import anilibria.apigen.models.EnumsanimecatalogfilterpublishStatus
import anilibria.apigen.models.Enumsanimecatalogfiltersorting
import anilibria.apigen.models.EnumsanimereleasesreleaseageRating
import anilibria.apigen.models.Enumsanimereleasesreleaseseason
import anilibria.apigen.models.Enumsanimereleasesreleasetype

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param genres 
 * @param types 
 * @param seasons 
 * @param years 
 * @param search 
 * @param sorting 
 * @param ageRatings 
 * @param publishStatuses 
 * @param productionStatuses 
 */
@JsonClass(generateAdapter = true)

data class AnimeCatalogReleasesPostRequestF (

    @Json(name = "genres")
    val genres: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "types")
    val types: kotlin.collections.List<Enumsanimereleasesreleasetype>? = null,

    @Json(name = "seasons")
    val seasons: kotlin.collections.List<Enumsanimereleasesreleaseseason>? = null,

    @Json(name = "years")
    val years: AnimeCatalogReleasesPostRequestFYears? = null,

    @Json(name = "search")
    val search: kotlin.String? = null,

    @Json(name = "sorting")
    val sorting: Enumsanimecatalogfiltersorting? = null,

    @Json(name = "age_ratings")
    val ageRatings: kotlin.collections.List<EnumsanimereleasesreleaseageRating>? = null,

    @Json(name = "publish_statuses")
    val publishStatuses: kotlin.collections.List<EnumsanimecatalogfilterpublishStatus>? = null,

    @Json(name = "production_statuses")
    val productionStatuses: kotlin.collections.List<EnumsanimecatalogfilterproductionStatus>? = null

) {


}

