/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.AnimeCatalogReleasesPostRequestF

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param limit 
 * @param f 
 */
@JsonClass(generateAdapter = true)

data class AnimeCatalogReleasesPostRequest (

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "f")
    val f: AnimeCatalogReleasesPostRequestF? = null

) {


}

