/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param previous 
 * @param next 
 */
@JsonClass(generateAdapter = true)

data class CommonsV1UtilsPaginationSchemesMetaLinks (

    @Json(name = "previous")
    val previous: kotlin.String? = null,

    @Json(name = "next")
    val next: kotlin.String? = null

) {


}

