/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ошибка валидации  параметров
 *
 * @param errors 
 */
@JsonClass(generateAdapter = true)

data class Commonsv1httpresponses422content (

    @Json(name = "errors")
    val errors: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null

) {


}

