/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.CommonsV1UtilsPaginationSchemesMetaLinks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total 
 * @param count 
 * @param perPage 
 * @param currentPage 
 * @param totalPages 
 * @param links 
 */
@JsonClass(generateAdapter = true)

data class Commonsv1utilspaginationschemesmeta (

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "per_page")
    val perPage: kotlin.Int? = null,

    @Json(name = "current_page")
    val currentPage: kotlin.Int? = null,

    @Json(name = "total_pages")
    val totalPages: kotlin.Int? = null,

    @Json(name = "links")
    val links: CommonsV1UtilsPaginationSchemesMetaLinks? = null

) {


}

