/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param preview Ссылка на изображение
 * @param thumbnail Ссылка на изображение
 */
@JsonClass(generateAdapter = true)

data class Commonsv1modelscomponentsimage (

    /* Ссылка на изображение */
    @Json(name = "preview")
    val preview: kotlin.String? = null,

    /* Ссылка на изображение */
    @Json(name = "thumbnail")
    val thumbnail: kotlin.String? = null

) {


}

