/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: CREATED_AT_DESC,CREATED_AT_ASC,FRESH_AT_DESC,FRESH_AT_ASC,RATING_DESC,RATING_ASC,YEAR_DESC,YEAR_ASC
 */

@JsonClass(generateAdapter = false)
enum class Enumsaccountsusersuserfavoritefiltersorting(val value: kotlin.String) {

    @Json(name = "CREATED_AT_DESC")
    CREATED_AT_DESC("CREATED_AT_DESC"),

    @Json(name = "CREATED_AT_ASC")
    CREATED_AT_ASC("CREATED_AT_ASC"),

    @Json(name = "FRESH_AT_DESC")
    FRESH_AT_DESC("FRESH_AT_DESC"),

    @Json(name = "FRESH_AT_ASC")
    FRESH_AT_ASC("FRESH_AT_ASC"),

    @Json(name = "RATING_DESC")
    RATING_DESC("RATING_DESC"),

    @Json(name = "RATING_ASC")
    RATING_ASC("RATING_ASC"),

    @Json(name = "YEAR_DESC")
    YEAR_DESC("YEAR_DESC"),

    @Json(name = "YEAR_ASC")
    YEAR_ASC("YEAR_ASC");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsaccountsusersuserfavoritefiltersorting) "$data" else null

        /**
         * Returns a valid [Enumsaccountsusersuserfavoritefiltersorting] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsaccountsusersuserfavoritefiltersorting? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

