/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: TV,ONA,WEB,OVA,OAD,MOVIE,DORAMA,SPECIAL
 */

@JsonClass(generateAdapter = false)
enum class Enumsanimereleasesreleasetype(val value: kotlin.String) {

    @Json(name = "TV")
    TV("TV"),

    @Json(name = "ONA")
    ONA("ONA"),

    @Json(name = "WEB")
    WEB("WEB"),

    @Json(name = "OVA")
    OVA("OVA"),

    @Json(name = "OAD")
    OAD("OAD"),

    @Json(name = "MOVIE")
    MOVIE("MOVIE"),

    @Json(name = "DORAMA")
    DORAMA("DORAMA"),

    @Json(name = "SPECIAL")
    SPECIAL("SPECIAL");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsanimereleasesreleasetype) "$data" else null

        /**
         * Returns a valid [Enumsanimereleasesreleasetype] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsanimereleasesreleasetype? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

