/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: IS_ONGOING,IS_NOT_ONGOING
 */

@JsonClass(generateAdapter = false)
enum class EnumsanimecatalogfilterpublishStatus(val value: kotlin.String) {

    @Json(name = "IS_ONGOING")
    IS_ONGOING("IS_ONGOING"),

    @Json(name = "IS_NOT_ONGOING")
    IS_NOT_ONGOING("IS_NOT_ONGOING");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnumsanimecatalogfilterpublishStatus) "$data" else null

        /**
         * Returns a valid [EnumsanimecatalogfilterpublishStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnumsanimecatalogfilterpublishStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

