/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список возможных значений источника видео (тип релиза)
 *
 * Values: BDRip,HDRip,TVRip,WEBRip,DTVRip,DVDRip,HDTVRip,WEBMinusDL,WEBMinusDLRip
 */

@JsonClass(generateAdapter = false)
enum class Enumsanimetorrentstorrenttype(val value: kotlin.String) {

    @Json(name = "BDRip")
    BDRip("BDRip"),

    @Json(name = "HDRip")
    HDRip("HDRip"),

    @Json(name = "TVRip")
    TVRip("TVRip"),

    @Json(name = "WEBRip")
    WEBRip("WEBRip"),

    @Json(name = "DTVRip")
    DTVRip("DTVRip"),

    @Json(name = "DVDRip")
    DVDRip("DVDRip"),

    @Json(name = "HDTVRip")
    HDTVRip("HDTVRip"),

    @Json(name = "WEB-DL")
    WEBMinusDL("WEB-DL"),

    @Json(name = "WEB-DLRip")
    WEBMinusDLRip("WEB-DLRip");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsanimetorrentstorrenttype) "$data" else null

        /**
         * Returns a valid [Enumsanimetorrentstorrenttype] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsanimetorrentstorrenttype? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

