/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список возможных значений качества видео в торренте
 *
 * Values: _360p,_480p,_576p,_720p,_1080p,_2k,_4k,_8k
 */

@JsonClass(generateAdapter = false)
enum class Enumsanimetorrentstorrentquality(val value: kotlin.String) {

    @Json(name = "360p")
    _360p("360p"),

    @Json(name = "480p")
    _480p("480p"),

    @Json(name = "576p")
    _576p("576p"),

    @Json(name = "720p")
    _720p("720p"),

    @Json(name = "1080p")
    _1080p("1080p"),

    @Json(name = "2k")
    _2k("2k"),

    @Json(name = "4k")
    _4k("4k"),

    @Json(name = "8k")
    _8k("8k");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsanimetorrentstorrentquality) "$data" else null

        /**
         * Returns a valid [Enumsanimetorrentstorrentquality] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsanimetorrentstorrentquality? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

