/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список возможных значений кодека видеодорожки в торренте
 *
 * Values: AV1,x264SlashAVC,x265SlashHEVC,x265hqSlashHEVCMinusHQ
 */

@JsonClass(generateAdapter = false)
enum class Enumsanimetorrentstorrentcodec(val value: kotlin.String) {

    @Json(name = "AV1")
    AV1("AV1"),

    @Json(name = "x264/AVC")
    x264SlashAVC("x264/AVC"),

    @Json(name = "x265/HEVC")
    x265SlashHEVC("x265/HEVC"),

    @Json(name = "x265hq/HEVC-HQ")
    x265hqSlashHEVCMinusHQ("x265hq/HEVC-HQ");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsanimetorrentstorrentcodec) "$data" else null

        /**
         * Returns a valid [Enumsanimetorrentstorrentcodec] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsanimetorrentstorrentcodec? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

