/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Роль участника релиза
 *
 * Values: poster,timing,voicing,editing,decorating,translating
 */

@JsonClass(generateAdapter = false)
enum class Enumsanimereleasesreleasememberrole(val value: kotlin.String) {

    @Json(name = "poster")
    poster("poster"),

    @Json(name = "timing")
    timing("timing"),

    @Json(name = "voicing")
    voicing("voicing"),

    @Json(name = "editing")
    editing("editing"),

    @Json(name = "decorating")
    decorating("decorating"),

    @Json(name = "translating")
    translating("translating");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsanimereleasesreleasememberrole) "$data" else null

        /**
         * Returns a valid [Enumsanimereleasesreleasememberrole] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsanimereleasesreleasememberrole? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

