/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип коллекции
 *
 * Values: PLANNED,WATCHED,WATCHING,POSTPONED,ABANDONED
 */

@JsonClass(generateAdapter = false)
enum class Enumsaccountsusersusercollectiontype(val value: kotlin.String) {

    @Json(name = "PLANNED")
    PLANNED("PLANNED"),

    @Json(name = "WATCHED")
    WATCHED("WATCHED"),

    @Json(name = "WATCHING")
    WATCHING("WATCHING"),

    @Json(name = "POSTPONED")
    POSTPONED("POSTPONED"),

    @Json(name = "ABANDONED")
    ABANDONED("ABANDONED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Enumsaccountsusersusercollectiontype) "$data" else null

        /**
         * Returns a valid [Enumsaccountsusersusercollectiontype] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Enumsaccountsusersusercollectiontype? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

