/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: R0_PLUS,R6_PLUS,R12_PLUS,R16_PLUS,R18_PLUS
 */

@JsonClass(generateAdapter = false)
enum class EnumsanimereleasesreleaseageRating(val value: kotlin.String) {

    @Json(name = "R0_PLUS")
    R0_PLUS("R0_PLUS"),

    @Json(name = "R6_PLUS")
    R6_PLUS("R6_PLUS"),

    @Json(name = "R12_PLUS")
    R12_PLUS("R12_PLUS"),

    @Json(name = "R16_PLUS")
    R16_PLUS("R16_PLUS"),

    @Json(name = "R18_PLUS")
    R18_PLUS("R18_PLUS");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnumsanimereleasesreleaseageRating) "$data" else null

        /**
         * Returns a valid [EnumsanimereleasesreleaseageRating] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnumsanimereleasesreleaseageRating? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

