/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.ModelsUsersV1UserSessionBrowser
import anilibria.apigen.models.ModelsUsersV1UserSessionDevice
import anilibria.apigen.models.ModelsUsersV1UserSessionLocation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по сессии пользователя
 *
 * @param id Transform pattern
 * @param userId 
 * @param device 
 * @param browser 
 * @param location 
 * @param isMobile Мобильное устройство
 * @param isDesktop Десктопное устройство
 * @param ipAddress IP-адрес
 * @param userAgent User-Agent
 * @param isCurrent Текущая сессия
 * @param lastActive 
 */
@JsonClass(generateAdapter = true)

data class Modelsusersv1usersession (

    /* Transform pattern */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "user_id")
    val userId: kotlin.Int? = null,

    @Json(name = "device")
    val device: ModelsUsersV1UserSessionDevice? = null,

    @Json(name = "browser")
    val browser: ModelsUsersV1UserSessionBrowser? = null,

    @Json(name = "location")
    val location: ModelsUsersV1UserSessionLocation? = null,

    /* Мобильное устройство */
    @Json(name = "is_mobile")
    val isMobile: kotlin.Boolean? = null,

    /* Десктопное устройство */
    @Json(name = "is_desktop")
    val isDesktop: kotlin.Boolean? = null,

    /* IP-адрес */
    @Json(name = "ip_address")
    val ipAddress: kotlin.String? = null,

    /* User-Agent */
    @Json(name = "user_agent")
    val userAgent: kotlin.String? = null,

    /* Текущая сессия */
    @Json(name = "is_current")
    val isCurrent: kotlin.Boolean? = null,

    @Json(name = "last_active")
    val lastActive: kotlin.String? = null

) {


}

