/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по аккаунту пользователю
 *
 * @param id ID анилибрийца
 * @param nickname Псевдоним анилибрийца в команде
 * @param avatar 
 */
@JsonClass(generateAdapter = true)

data class Modelsteamsv1teamuseraccount (

    /* ID анилибрийца */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Псевдоним анилибрийца в команде */
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: Commonsv1modelscomponentsimagewithOptimized? = null

) {


}

