/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsanimereleasesv1releasememberrole
import anilibria.apigen.models.Modelsanimereleasesv1releasememberuser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Участник релиза
 *
 * @param id 
 * @param role 
 * @param user Связанный с участником релиза пользователь
 * @param nickname 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releasemember (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "role")
    val role: Modelsanimereleasesv1releasememberrole? = null,

    /* Связанный с участником релиза пользователь */
    @Json(name = "user")
    val user: Modelsanimereleasesv1releasememberuser? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null

) {


}

