/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.Modelsanimereleasesv1releaseepisodeskip

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Эпизод релиза
 *
 * @param id Идентификатор эпизода
 * @param name Название эпизода
 * @param ordinal Номер эпизода. Может быть целым или дробным числом (например, 5 или 23.5)
 * @param ending 
 * @param opening 
 * @param preview 
 * @param hls480 Ссылка на поток 480p
 * @param hls720 Ссылка на поток 720p
 * @param hls1080 Ссылка на поток 1080p
 * @param duration Длительность эпизода в секундах
 * @param rutubeId Id эпизода на Rutube
 * @param youtubeId Id эпизода на Youtube
 * @param updatedAt Дата обновления эпизода
 * @param sortOrder Порядковый номер эпизода для сортировки
 * @param nameEnglish Название эпизода на английском
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releaseepisode (

    /* Идентификатор эпизода */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Название эпизода */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Номер эпизода. Может быть целым или дробным числом (например, 5 или 23.5) */
    @Json(name = "ordinal")
    val ordinal: java.math.BigDecimal? = null,

    @Json(name = "ending")
    val ending: Modelsanimereleasesv1releaseepisodeskip? = null,

    @Json(name = "opening")
    val opening: Modelsanimereleasesv1releaseepisodeskip? = null,

    @Json(name = "preview")
    val preview: Commonsv1modelscomponentsimagewithOptimized? = null,

    /* Ссылка на поток 480p */
    @Json(name = "hls_480")
    val hls480: kotlin.String? = null,

    /* Ссылка на поток 720p */
    @Json(name = "hls_720")
    val hls720: kotlin.String? = null,

    /* Ссылка на поток 1080p */
    @Json(name = "hls_1080")
    val hls1080: kotlin.String? = null,

    /* Длительность эпизода в секундах */
    @Json(name = "duration")
    val duration: kotlin.Int? = null,

    /* Id эпизода на Rutube */
    @Json(name = "rutube_id")
    val rutubeId: kotlin.String? = null,

    /* Id эпизода на Youtube */
    @Json(name = "youtube_id")
    val youtubeId: kotlin.String? = null,

    /* Дата обновления эпизода */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* Порядковый номер эпизода для сортировки */
    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    /* Название эпизода на английском */
    @Json(name = "name_english")
    val nameEnglish: kotlin.String? = null

) {


}

