/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.Modelsanimereleasesv1release

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по промо-материалам
 *
 * @param id 
 * @param url Кастомная ссылка на промо-материал
 * @param urlLabel Кастомная подпись к ссылке
 * @param image 
 * @param title Кастомное название промо-материала
 * @param description Кастомное описание промо-материала
 * @param isAd Флаг рекламной промо кампании
 * @param adErid 
 * @param adOrigin 
 * @param release 
 * @param hasOverlay Использовать темный оверлей
 */
@JsonClass(generateAdapter = true)

data class Modelsmediapromotionsv1promotion (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Кастомная ссылка на промо-материал */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Кастомная подпись к ссылке */
    @Json(name = "url_label")
    val urlLabel: kotlin.String? = null,

    @Json(name = "image")
    val image: Commonsv1modelscomponentsimagewithOptimized? = null,

    /* Кастомное название промо-материала */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Кастомное описание промо-материала */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Флаг рекламной промо кампании */
    @Json(name = "is_ad")
    val isAd: kotlin.Boolean? = null,

    @Json(name = "ad_erid")
    val adErid: kotlin.String? = null,

    @Json(name = "ad_origin")
    val adOrigin: kotlin.String? = null,

    @Json(name = "release")
    val release: Modelsanimereleasesv1release? = null,

    /* Использовать темный оверлей */
    @Json(name = "has_overlay")
    val hasOverlay: kotlin.Boolean? = null

) {


}

