/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по релизам в франшизе
 *
 * @param id ID связки релиз — франшиза
 * @param sortOrder Порядок сортировки
 * @param releaseId Идентификатор релиза
 * @param franchiseId Идентификатор франшизы
 */
@JsonClass(generateAdapter = true)

data class Modelsanimefranchisesv1franchiserelease (

    /* ID связки релиз — франшиза */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Порядок сортировки */
    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    /* Идентификатор релиза */
    @Json(name = "release_id")
    val releaseId: kotlin.Int? = null,

    /* Идентификатор франшизы */
    @Json(name = "franchise_id")
    val franchiseId: kotlin.String? = null

) {


}

