/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация об устройстве
 *
 * @param name 
 * @param version 
 * @param platform 
 */
@JsonClass(generateAdapter = true)

data class ModelsUsersV1UserSessionDevice (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "platform")
    val platform: kotlin.String? = null

) {


}

