/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по анилибрийцу
 *
 * @param id ID анилибрийца
 * @param nickname Псевдоним анилибрийца в команде
 * @param isIntern Флаг, указывающий, является ли пользователь стажером
 * @param sortOrder Порядок сортировки внутри команды
 * @param isVacation Флаг, указывающий, находится ли пользователь в отпуске
 */
@JsonClass(generateAdapter = true)

data class Modelsteamsv1teamuser (

    /* ID анилибрийца */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Псевдоним анилибрийца в команде */
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    /* Флаг, указывающий, является ли пользователь стажером */
    @Json(name = "is_intern")
    val isIntern: kotlin.Boolean? = null,

    /* Порядок сортировки внутри команды */
    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    /* Флаг, указывающий, находится ли пользователь в отпуске */
    @Json(name = "is_vacation")
    val isVacation: kotlin.Boolean? = null

) {


}

