/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по роли в команде
 *
 * @param id ID роли
 * @param title Название роли
 * @param color Цвет
 * @param sortOrder Порядок сортировки роли
 */
@JsonClass(generateAdapter = true)

data class Modelsteamsv1teamrole (

    /* ID роли */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Название роли */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Цвет */
    @Json(name = "color")
    val color: kotlin.String? = null,

    /* Порядок сортировки роли */
    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null

) {


}

