/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по спонсорам
 *
 * @param id Transform pattern
 * @param title 
 * @param description 
 * @param urlTitle 
 * @param url 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimesponsorsv1sponsor (

    /* Transform pattern */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "url_title")
    val urlTitle: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null

) {


}

