/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Геолокация пользователя
 *
 * @param country 
 * @param isoCode 
 */
@JsonClass(generateAdapter = true)

data class ModelsUsersV1UserSessionLocation (

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "iso_code")
    val isoCode: kotlin.String? = null

) {


}

