/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тайминги пропуска опенинга или эндинга
 *
 * @param start Время начала. Количество секунд от начала или конца эпизода
 * @param stop Время окончания. Количество секунд от начала или конца эпизода
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releaseepisodeskip (

    /* Время начала. Количество секунд от начала или конца эпизода */
    @Json(name = "start")
    val start: kotlin.Int? = null,

    /* Время окончания. Количество секунд от начала или конца эпизода */
    @Json(name = "stop")
    val stop: kotlin.Int? = null

) {


}

