/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsanimetorrentstorrentcodec

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о кодеке видео в торренте
 *
 * @param `value` 
 * @param label 
 * @param description 
 * @param labelColor Цвет лейбла
 * @param labelIsVisible Отображать ли лейбл рядом с торрентом
 */
@JsonClass(generateAdapter = true)

data class Modelsanimetorrentsv1torrentcodec (

    @Json(name = "value")
    val `value`: Enumsanimetorrentstorrentcodec? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Цвет лейбла */
    @Json(name = "label_color")
    val labelColor: kotlin.String? = null,

    /* Отображать ли лейбл рядом с торрентом */
    @Json(name = "label_is_visible")
    val labelIsVisible: kotlin.Boolean? = null

) {


}

