/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по связанному с участником торрента пользователю
 *
 * @param id 
 * @param avatar 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimetorrentsv1torrentmemberuser (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "avatar")
    val avatar: Commonsv1modelscomponentsimagewithOptimized? = null

) {


}

