/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.Enumsadsbannerplacement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные рекламного баннера
 *
 * @param id 
 * @param title 
 * @param image 
 * @param adErid 
 * @param imageUrl 
 * @param buttonUrl 
 * @param placement 
 * @param hasOverlay 
 * @param buttonTitle 
 * @param description 
 * @param adCompanyItn 
 * @param adCompanyName 
 */
@JsonClass(generateAdapter = true)

data class Modelsadsbannersv1banner (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "image")
    val image: Commonsv1modelscomponentsimagewithOptimized? = null,

    @Json(name = "ad_erid")
    val adErid: kotlin.String? = null,

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "button_url")
    val buttonUrl: kotlin.String? = null,

    @Json(name = "placement")
    val placement: Enumsadsbannerplacement? = null,

    @Json(name = "has_overlay")
    val hasOverlay: kotlin.Boolean? = null,

    @Json(name = "button_title")
    val buttonTitle: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "ad_company_itn")
    val adCompanyItn: kotlin.String? = null,

    @Json(name = "ad_company_name")
    val adCompanyName: kotlin.String? = null

) {


}

