/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsanimereleasesreleasememberrole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Роль участника релиза
 *
 * @param `value` 
 * @param description 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releasememberrole (

    @Json(name = "value")
    val `value`: Enumsanimereleasesreleasememberrole? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

