/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по торрентам
 *
 * @param passkey passkey, отображается только собственный
 * @param uploaded Количество отданного, в байтах
 * @param downloaded Количество скачанного, в байтах
 */
@JsonClass(generateAdapter = true)

data class ModelsUsersV1UserTorrents (

    /* passkey, отображается только собственный */
    @Json(name = "passkey")
    val passkey: kotlin.String? = null,

    /* Количество отданного, в байтах */
    @Json(name = "uploaded")
    val uploaded: kotlin.Int? = null,

    /* Количество скачанного, в байтах */
    @Json(name = "downloaded")
    val downloaded: kotlin.Int? = null

) {


}

