/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Название релиза
 *
 * @param main 
 * @param english 
 * @param alternative 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releasename (

    @Json(name = "main")
    val main: kotlin.String? = null,

    @Json(name = "english")
    val english: kotlin.String? = null,

    @Json(name = "alternative")
    val alternative: kotlin.String? = null

) {


}

