/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.ModelsUsersV1UserTorrents

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по пользователю
 *
 * @param id Transform pattern
 * @param login Отображается только собственный
 * @param email Отображается только собственный
 * @param nickname 
 * @param avatar 
 * @param torrents 
 * @param isBanned Забанен ли пользоваель в данный момент
 * @param createdAt 
 * @param isWithAds Отображение рекламы
 */
@JsonClass(generateAdapter = true)

data class Modelsusersv1user (

    /* Transform pattern */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Отображается только собственный */
    @Json(name = "login")
    val login: kotlin.String? = null,

    /* Отображается только собственный */
    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: Commonsv1modelscomponentsimagewithOptimized? = null,

    @Json(name = "torrents")
    val torrents: ModelsUsersV1UserTorrents? = null,

    /* Забанен ли пользоваель в данный момент */
    @Json(name = "is_banned")
    val isBanned: kotlin.Boolean? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    /* Отображение рекламы */
    @Json(name = "is_with_ads")
    val isWithAds: kotlin.Boolean? = null

) {


}

