/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.EnumsanimereleasesreleaseageRating

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Возрастное ограничение
 *
 * @param `value` 
 * @param label 
 * @param isAdult 
 * @param description 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releaseageRating (

    @Json(name = "value")
    val `value`: EnumsanimereleasesreleaseageRating? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "is_adult")
    val isAdult: kotlin.Boolean? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

