/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по OTP коду
 *
 * @param code 
 * @param userId 
 * @param deviceId 
 * @param expiredAt Срок действия кода
 */
@JsonClass(generateAdapter = true)

data class Modelsaccountsotpv1otp (

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "user_id")
    val userId: kotlin.Int? = null,

    @Json(name = "device_id")
    val deviceId: kotlin.String? = null,

    /* Срок действия кода */
    @Json(name = "expired_at")
    val expiredAt: kotlin.String? = null

) {


}

