/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsmediavideosv1videoorigintype

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по видео-источнику
 *
 * @param id 
 * @param url 
 * @param type 
 * @param title 
 * @param description 
 * @param isAnnounce Видео-источник является анонсом сезона
 */
@JsonClass(generateAdapter = true)

data class Modelsmediavideosv1videoorigin (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "type")
    val type: Modelsmediavideosv1videoorigintype? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Видео-источник является анонсом сезона */
    @Json(name = "is_announce")
    val isAnnounce: kotlin.Boolean? = null

) {


}

