/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по рекламе VAST
 *
 * @param id 
 * @param url 
 * @param adErid 
 * @param adCompanyItn 
 * @param adCompanyName 
 */
@JsonClass(generateAdapter = true)

data class Modelsadsvastsv1vast (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "ad_erid")
    val adErid: kotlin.String? = null,

    @Json(name = "ad_company_itn")
    val adCompanyItn: kotlin.String? = null,

    @Json(name = "ad_company_name")
    val adCompanyName: kotlin.String? = null

) {


}

