/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsanimereleasesreleaseseason

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Сезон релиза
 *
 * @param `value` 
 * @param description 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimereleasesv1releaseseason (

    @Json(name = "value")
    val `value`: Enumsanimereleasesreleaseseason? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

