/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по команде
 *
 * @param id ID команды
 * @param title Название команды
 * @param sortOrder Порядок сортировки команды
 * @param description Описание команды
 */
@JsonClass(generateAdapter = true)

data class Modelsteamsv1team (

    /* ID команды */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Название команды */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Порядок сортировки команды */
    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    /* Описание команды */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

