/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsanimereleasesv1release
import anilibria.apigen.models.Modelsanimereleasesv1releaseepisode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные по релизу в расписании
 *
 * @param release 
 * @param fullSeasonIsReleased 
 * @param publishedReleaseEpisode 
 * @param nextReleaseEpisodeNumber 
 */
@JsonClass(generateAdapter = true)

data class Modelsanimeschedulev1releaseInSchedule (

    @Json(name = "release")
    val release: Modelsanimereleasesv1release? = null,

    @Json(name = "full_season_is_released")
    val fullSeasonIsReleased: kotlin.Boolean? = null,

    @Json(name = "published_release_episode")
    val publishedReleaseEpisode: Modelsanimereleasesv1releaseepisode? = null,

    @Json(name = "next_release_episode_number")
    val nextReleaseEpisodeNumber: kotlin.Int? = null

) {


}

