/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param image 
 * @param totalReleases Общее количество релизов в этом жанре
 */
@JsonClass(generateAdapter = true)

data class Responsesapiv1animegenresitem (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "image")
    val image: Commonsv1modelscomponentsimagewithOptimized? = null,

    /* Общее количество релизов в этом жанре */
    @Json(name = "total_releases")
    val totalReleases: kotlin.Int? = null

) {


}

