/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.ResponsesV1AnimeFranchiseDataAllOfFranchiseReleasesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Идентификатор франшизы
 * @param name Название франшизы (на русском)
 * @param nameEnglish Название франшизы (на английском)
 * @param image 
 * @param rating Рейтинг франшизы
 * @param lastYear Год последнего релиза
 * @param firstYear Год первого релиза
 * @param totalReleases Количество релизов
 * @param totalEpisodes Общее количество эпизодов
 * @param totalDuration Общая длительность франшизы
 * @param totalDurationInSeconds Общая длительность франшизы в секундах
 * @param franchiseReleases 
 */
@JsonClass(generateAdapter = true)

data class ResponsesV1AnimeFranchiseData (

    /* Идентификатор франшизы */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Название франшизы (на русском) */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Название франшизы (на английском) */
    @Json(name = "name_english")
    val nameEnglish: kotlin.String? = null,

    @Json(name = "image")
    val image: Commonsv1modelscomponentsimagewithOptimized? = null,

    /* Рейтинг франшизы */
    @Json(name = "rating")
    val rating: java.math.BigDecimal? = null,

    /* Год последнего релиза */
    @Json(name = "last_year")
    val lastYear: kotlin.Int? = null,

    /* Год первого релиза */
    @Json(name = "first_year")
    val firstYear: kotlin.Int? = null,

    /* Количество релизов */
    @Json(name = "total_releases")
    val totalReleases: kotlin.Int? = null,

    /* Общее количество эпизодов */
    @Json(name = "total_episodes")
    val totalEpisodes: kotlin.Int? = null,

    /* Общая длительность франшизы */
    @Json(name = "total_duration")
    val totalDuration: kotlin.String? = null,

    /* Общая длительность франшизы в секундах */
    @Json(name = "total_duration_in_seconds")
    val totalDurationInSeconds: kotlin.Int? = null,

    @Json(name = "franchise_releases")
    val franchiseReleases: kotlin.collections.List<ResponsesV1AnimeFranchiseDataAllOfFranchiseReleasesInner>? = null

) {


}

