/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1utilspaginationschemesmeta
import anilibria.apigen.models.ResponsesV1AccountsUsersCollectionsReleasesDataInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param meta 
 */
@JsonClass(generateAdapter = true)

data class Responsesv1accountsuserscollectionsreleases (

    @Json(name = "data")
    val `data`: kotlin.collections.List<ResponsesV1AccountsUsersCollectionsReleasesDataInner>? = null,

    @Json(name = "meta")
    val meta: Commonsv1utilspaginationschemesmeta? = null

) {


}

