/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsaccountsusersuserfavoritefiltersorting

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `value` 
 * @param label Название опции сортировки
 * @param description Описание опции сортировки
 */
@JsonClass(generateAdapter = true)

data class ResponsesApiV1AccountsUsersMeFavoritesReferencesSortingInner (

    @Json(name = "value")
    val `value`: Enumsaccountsusersuserfavoritefiltersorting? = null,

    /* Название опции сортировки */
    @Json(name = "label")
    val label: kotlin.String? = null,

    /* Описание опции сортировки */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

