/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token JWT токен авторизации
 */
@JsonClass(generateAdapter = true)

data class Responsesv1accountsusersauthsocialauthenticate (

    /* JWT токен авторизации */
    @Json(name = "token")
    val token: kotlin.String? = null

) {


}

