/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Идентификатор жанра
 * @param name Название жанра
 */
@JsonClass(generateAdapter = true)

data class ResponsesApiV1AccountsUsersMeCollectionsReferencesGenresInner (

    /* Идентификатор жанра */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Название жанра */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

