/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url Ссылка на oauth авторизацию через указанную социальную сеть
 * @param state Ключ для аутентификации пройденной авторизации
 */
@JsonClass(generateAdapter = true)

data class Responsesv1accountsusersauthsociallogin (

    /* Ссылка на oauth авторизацию через указанную социальную сеть */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Ключ для аутентификации пройденной авторизации */
    @Json(name = "state")
    val state: kotlin.String? = null

) {


}

