/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Commonsv1modelscomponentsimagewithOptimized
import anilibria.apigen.models.Modelsmediavideosv1videoorigin

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param url 
 * @param title 
 * @param views Количество просмотров ролика
 * @param image 
 * @param comments Количество комментариев под роликом
 * @param videoId 
 * @param createdAt 
 * @param updatedAt Дата последнего обновления данных
 * @param isAnnounce Видео является анонсом сезона
 * @param origin 
 */
@JsonClass(generateAdapter = true)

data class ResponsesV1MediaVideosDataInner (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Количество просмотров ролика */
    @Json(name = "views")
    val views: kotlin.Int? = null,

    @Json(name = "image")
    val image: Commonsv1modelscomponentsimagewithOptimized? = null,

    /* Количество комментариев под роликом */
    @Json(name = "comments")
    val comments: kotlin.Int? = null,

    @Json(name = "video_id")
    val videoId: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    /* Дата последнего обновления данных */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* Видео является анонсом сезона */
    @Json(name = "is_announce")
    val isAnnounce: kotlin.Boolean? = null,

    @Json(name = "origin")
    val origin: Modelsmediavideosv1videoorigin? = null

) {


}

