/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsmediapromotionsv1promotion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 */
@JsonClass(generateAdapter = true)

data class Responsesv1mediapromotions (

    @Json(name = "data")
    val `data`: kotlin.collections.List<Modelsmediapromotionsv1promotion>? = null

) {


}

