/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Enumsanimereleasesreleasetype

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `value` 
 * @param description Описание типа
 */
@JsonClass(generateAdapter = true)

data class ResponsesApiV1AccountsUsersMeCollectionsReferencesTypesInner (

    @Json(name = "value")
    val `value`: Enumsanimereleasesreleasetype? = null,

    /* Описание типа */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

