/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsanimeschedulev1releaseInSchedule

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param today 
 * @param tomorrow 
 * @param yesterday 
 */
@JsonClass(generateAdapter = true)

data class Responsesv1animeschedulenow (

    @Json(name = "today")
    val today: kotlin.collections.List<Modelsanimeschedulev1releaseInSchedule>? = null,

    @Json(name = "tomorrow")
    val tomorrow: kotlin.collections.List<Modelsanimeschedulev1releaseInSchedule>? = null,

    @Json(name = "yesterday")
    val yesterday: kotlin.collections.List<Modelsanimeschedulev1releaseInSchedule>? = null

) {


}

