/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsaccountsotpv1otp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param otp 
 * @param remainingTime 
 */
@JsonClass(generateAdapter = true)

data class Responsesapiv1accountsotpget (

    @Json(name = "otp")
    val otp: Modelsaccountsotpv1otp? = null,

    @Json(name = "remaining_time")
    val remainingTime: kotlin.Int? = null

) {


}

