/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package anilibria.apigen.models

import anilibria.apigen.models.Modelsanimetorrentsv1torrentmemberrole
import anilibria.apigen.models.Modelsanimetorrentsv1torrentmemberuser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param role 
 * @param nickname 
 * @param externalUrl 
 * @param user 
 */
@JsonClass(generateAdapter = true)

data class ResponsesApiV1AnimeTorrentAllOfTorrentMembers (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "role")
    val role: Modelsanimetorrentsv1torrentmemberrole? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "external_url")
    val externalUrl: kotlin.String? = null,

    @Json(name = "user")
    val user: Modelsanimetorrentsv1torrentmemberuser? = null

) {


}

